(copy_files ../assembly/*.mly)
(copy_files ../assembly/lexer.mll)

(ocamllex lexer)

(menhir
 (modules token_spec common_parser parser)
 (merge_into generated_parser)
 (flags
  --strict
  --unused-token MUL
  --unused-token REM
  --unused-token DIV
  --unused-token GETOTYPE
  --unused-token GETWTYPE
  --unused-token SEAL
  --unused-token UNSEAL
  --unused-token INVOKE
  --unused-token SEAL_PERMISSION
  --unused-token WORD_TYPE
  --unused-token LBRACKET
  --unused-token RBRACKET
  --unused-token LBRACE
  --unused-token RBRACE
  --unused-token EINIT
  --unused-token EDEINIT
  --unused-token ESTOREID
  --unused-token ISUNIQUE))

(library
 (name cerise_ucerise_private)
 (package cerise-interpreter)
 (wrapped true)
 (libraries cerise_core menhirLib zarith)
 (flags (:standard -open Cerise_core)))
