(copy_files ../assembly/*.mly)
(copy_files ../assembly/lexer.mll)

(ocamllex lexer)

(menhir
 (modules token_spec common_parser parser)
 (merge_into generated_parser)
 (flags
  --strict
  --unused-token JALR
  --unused-token READSR
  --unused-token WRITESR
  --unused-token LAND
  --unused-token LOR
  --unused-token LSHIFTL
  --unused-token LSHIFTR
  --unused-token SYSTEM_REGISTER
  --unused-token GRIOTTE_PERMISSION
  --unused-precedence-levels
  --unused-token LOADU
  --unused-token STOREU
  --unused-token ISPTR
  --unused-token PROMOTEU
  --unused-token EINIT
  --unused-token EDEINIT
  --unused-token ESTOREID
  --unused-token ISUNIQUE))

(library
 (name cerise_locality_cerise_private)
 (package cerise-interpreter)
 (wrapped true)
 (libraries cerise_core menhirLib zarith)
 (flags (:standard -open Cerise_core)))
