/* Shared lexical token universe for every generated backend parser. A token's presence here means
   the lexer can classify it; only a backend's own [grammar.mly] can make that token valid syntax. */

%token <Z.t> INTEGER
%token <string> IDENT REGISTER PARAMETER CALL PERMISSION SEAL_PERMISSION LOCALITY WORD_TYPE
%token DEFINE MACRO ENDMACRO
%token CURRENT_ADDRESS MAX_ADDRESS STACK_ADDRESS
%token <string> JMP JNZ MOVE LOAD STORE ADD SUB MUL REM DIV LT LEA RESTRICT SUBSEG
%token <string> GETL GETB GETE GETA GETP GETOTYPE GETWTYPE SEAL UNSEAL INVOKE FAIL HALT
%token <string> LOADU STOREU ISPTR PROMOTEU
%token <string> EINIT EDEINIT ESTOREID ISUNIQUE
%token <string> HASH_WORD HASH_CONCAT
%token <string> JALR READSR WRITESR LAND LOR LSHIFTL LSHIFTR
%token <string> SYSTEM_REGISTER GRIOTTE_PERMISSION
%token LPAREN RPAREN LBRACKET RBRACKET LBRACE RBRACE COMMA COLON
%token PLUS MINUS STAR LOGAND LOGOR SHIFT_LEFT SHIFT_RIGHT HASH ASSIGN
%token EOF

%%
