name: CI

on: [push, pull_request]

# Prevent parallel CI: Stop every workflow of a branch
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        shell: bash
        run: echo "##[{name=branch};]$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git

      - name: Install dependencies
        run: opam install . --deps-only -y

      - name: Build
        run: opam exec -- make

      - name: Tests
        run: opam exec -- make test
