name: CI

on: [push, pull_request]

# Prevent parallel CI: Stop every workflow of a branch
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: nix build --print-build-logs

      - name: Format
        run: nix develop --command dune fmt
